SRCS=BedOverlaps.cpp
HDRS=BedOverlaps.hpp
EXE=BedOverlaps
CXX=/software/gcc-4.6.0/bin/g++
CXXFLAGS=-std=c++0x -O3  -Wl,-rpath,/software/gcc-4.6.0/lib64
$(EXE): $(SRCS) $(HDRS)
	$(CXX) $(CXXFLAGS) $(SRCS) -o $@


