SRCS=overlaps_in_narrow_peaks.cpp
HDRS=overlaps_in_narrow_peaks.hpp
EXE=overlaps_in_narrow_peaks
CXX=/software/gcc-4.6.0/bin/g++
CXXFLAGS=-std=c++0x -O3  -Wl,-rpath,/software/gcc-4.6.0/lib64
$(EXE): $(SRCS) $(HDRS)
	$(CXX) $(CXXFLAGS) $(SRCS) -o $@


