#CXXFLAGS=-O3
#merging_data_main


SRCS=merging_data_main.cpp
EXE=merging_data_main
CXX=/software/gcc-4.6.0/bin/g++
CXXFLAGS=-std=c++0x -O3  -Wl,-rpath,/software/gcc-4.6.0/lib64
$(EXE): $(SRCS)
	$(CXX) $(CXXFLAGS) $(SRCS) -o $@


